name: Continuous Deployment
on:
  workflow_dispatch:
  release:
    types: [published]
env:
  KUBE_CLUSTER: live-1.cloud-platform.service.justice.gov.uk
  NAMESPACE: dstest
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t foo .
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: eu-west-2
          local-image: foo
          image: webops/dstest-ecr:${{ github.sha }}
      - name: Apply to kubernetes
        run: export IMAGE_TAG=${{ github.sha }} && cat kubernetes-deploy.yaml | envsubst
      - name: Authenticate to the cluster
        run: |
          echo ${KUBE_CERT} > ca.crt
          ls -l ./ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://api.${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${KUBE_TOKEN}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}
          kubectl get pods
