name: Continuous Deployment
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t foo .
